version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - node-network

  nodejs:
    build: 
      context: node
    container_name: nodejs-container
    entrypoint: dockerize -wait tcp://mysql-container:3306 -timeout 20s docker-entrypoint.sh
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: testdb
    volumes:
      - .:/app
    command: ["npm", "start"]
    networks:
      - node-network

  nginx:
    build: 
      context: nginx
    container_name: nginx-container
    ports:
      - "80:80"
    depends_on:
      - nodejs
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - node-network

networks: 
  node-network:
    driver: bridge